// Airtable table and field IDs for ILS CRM base (appYXbUdcmSwBoPFU)
module.exports = {
  BASE_ID: 'appYXbUdcmSwBoPFU',

  TABLES: {
    CONTACTS: 'tbl9Q8m06ivkTYyvR',
    IMPORTED_CONTACTS: 'tblribgEf5RENNDQW',
    COMPANIES: 'tblEauAm0ZYuMbHUa',
    SPECIALTIES: 'tblysTixdxGQQntHO',
  },

  // Imported Contacts field IDs
  IC: {
    NAME: 'fldKc8P6eYXjMpAJ6',
    FIRST_NAME: 'fld7c1acCh17aOi0p',
    LAST_NAME: 'fldICvkgNbRG9dpqm',
    COMPANY: 'fld31Zl7X7DBZdL9K',
    JOB_TITLE: 'fldTHA6J24XaECMsz',
    EMAIL: 'fld9ejqJy5wjBqvrx',
    PHONE: 'fldZfFoFsOrIW2wQZ',
    MOBILE_PHONE: 'fldm8LaalVz7l38PS',
    WORK_PHONE: 'fld8MuOecNSVON5rD',
    LINKEDIN_URL: 'fldzikDES0UdCd4FQ',
    WEBSITE: 'fld57XgOQ9sFJOfof',
    TAGS: 'fldn2bUb5Khf7iumL',
    CATEGORIZATION: 'fldrYKTLd2HnL7GSe',
    SPECIALITY_MULTISELECT: 'fldTVm68nxYInyaUh',
    SPECIALTIES_LINKED: 'fldlkF1wlCbxBQ3KJ',
    ONBOARDING_STATUS: 'fldncdRP37p6BB9UX',
    SYNC_TO_CONTACTS: 'fldjm5mEIT25nlWjT',
    RELATED_CRM_CONTACT: 'fldDq3cetx5nrVqGo',
    ADDRESS_LINE: 'fld1Zpkm1Kms9XvRv',
    CITY: 'fldfS2EeVb5l3ic5h',
    STATE: 'fldIoe4TldH0WJUZj',
    COUNTRY: 'fldljgJjsqMkpMbkc',
    POSTAL_CODE: 'fldIsJaEWbMOb2juI',
    NOTES: 'fldMsJukGZt02TYVu',
    EVENT_TAGS: 'fldwI75ClzRJ7lli0',
    IMPORT_SOURCE: 'fld1fDiNE3vhoyi3P',
    IMPORT_DATE: 'fldNa8uThfClQFB79',
    COMPANY_DESCRIPTION: 'fldc5Aj4hRRZ4tIgE',
    COMPANY_INDUSTRY: 'fldiFajpEd7M14YBF',
    COMPANY_TYPE: 'fldiB3195PfAK7Wfg',
    COMPANY_SIZE: 'fldsJURWi2VvrvN2v',
    COMPANY_ANNUAL_REVENUE: 'fldLJr6gTu9zTeo0r',
    COMPANY_STREET: 'fldwAf4k6bsI922O4',
    COMPANY_CITY: 'fld4tMsuM8QhnhuZm',
    COMPANY_STATE: 'fldv9qnkGC3pnZQnv',
    COMPANY_COUNTRY: 'fld4YLilZ2HdhmCse',
    COMPANY_POSTAL_CODE: 'fldamMPu4kkZGugZn',
    COMPANY_FOUNDING_YEAR: 'fldCgacbjwFoRlHIp',
    COMPANY_NAICS_CODE: 'fldehmtkMRlb4M5Zi',
  },

  // Contacts field IDs
  C: {
    CONTACT_NAME: 'fldMkz6x5i8YaofZj',
    FIRST_NAME: 'fldBzVPUdMy99vfvp',
    LAST_NAME: 'fldq4VxEf0jJgi6O5',
    JOB_TITLE: 'fldvecarEW7fx90Ci',
    COMPANY_TEXT: 'fldTwuGnEhbQfZhP3',
    EMAIL: 'fldBjSvbdd5WXmoIG',
    PHONE: 'fldwF5NBjGVndCXNV',
    MOBILE_PHONE: 'fldwULn4qSjwzSOTj',
    WORK_PHONE: 'fldueNgIMN0Ui5MWw',
    SPECIALTIES_LINKED: 'fldPgiO2nKgcujeXz',
    COMPANIES_LINKED: 'fldYXDUc9YKKsGTBt',
    IMPORTED_CONTACTS_LINKED: 'fldj08SdhFcsYpRva',
    LINKEDIN_URL: 'fldWrrBfD7aLxsXT4',
    WEBSITE: 'fldnWic86lLjcF9MR',
    TAGS: 'fldO7kfLDA9jZswPB',
    CATEGORIZATION: 'fldofD9DQHfugTxsC',
    IMPORT_SOURCE: 'fldZG5LYBnFcEwhyw',
    IMPORT_DATE: 'fldoeYmeSZDrd7Y25',
    ONBOARDING_STATUS: 'fldbCsU8sEBNRm1kX',
    ADDRESS_LINE: 'fldxn8YVJ1pWGkaF8',
    CITY: 'fldAoanFJ1Fmrzkx5',
    STATE: 'fld1qq6PMLW6Ytbig',
    COUNTRY: 'fldnTdpTO4njtc4gZ',
    POSTAL_CODE: 'fldGgFJJ7XeLAR17a',
    NOTES: 'fldfbmMsacAKerGek',
    EVENT_TAGS: 'fld1D4u2KbIk0aUPR',
    LEAD_NOTE: 'fldWtoMSWdFla3dII',
  },

  // Companies field IDs
  CO: {
    COMPANY_NAME: 'fldVYiMOLq3LJgbZ3',
    TYPE: 'fldtLJxxK5oT6Nzjn',
    INDUSTRY: 'fldPz4rknFpmEXZAD',
    WEBSITE: 'fldVBnFiEeyDf9oCg',
    ADDRESS: 'fldyd3pnfJ5PCwwQD',
    CITY: 'fldJGkGiCoxduD4sg',
    STATE_REGION: 'fldNekCaGCR56MLcJ',
    COUNTRY: 'fldjvoxUo8iuKITjB',
    NOTES: 'flddUZDFk4l9f377V',
    CREATED_DATE: 'fldxQpzFGadejLLVp',
    CONTACTS_LINKED: 'fldQ2RK3PeAPMzkJB',
    COMPANY_DESCRIPTION: 'fldIDywGKU18pEndd',
    FOUNDING_YEAR: 'fldZaxAXqeImQcuzW',
    NAICS_CODE: 'fldL93N86XiMu5sUn',
    COMPANY_TYPE: 'fldSgiy8i2QUTmZbX',
    COMPANY_SIZE: 'fld0FFqLVasuvG9Uf',
    ANNUAL_REVENUE: 'fldMaVs106qf6Gmqp',
    POSTAL_CODE: 'fldqa7L8FPSeSQ9xG',
  },

  // Specialties field IDs
  S: {
    SPECIALTY_NAME: 'fldLVp1uePoKCuJlM',
    IMPORTED_CONTACTS: 'fldPQWyanCOcXVxmL',
    CONTACTS: 'fldVtUb9RqF03Ubq7',
  },
};
